[package]
name = "openvcs-git-libgit2"
version = "0.1.0"
edition = "2024"

[dependencies]
openvcs-core = { path = "../openvcs-core" }
git2 = "0.20"
thiserror = "2"
serde = "1.0.219"
linkme = "0.3"
log = "0.4" 
