name: Dev CI (fast)

on:
  push:
    branches: [ Dev ]
    paths:
      - 'Frontend/**'
      - 'Backend/**'
      - 'crates/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/development.yml'
  pull_request:
    branches: [ Dev ]
    paths:
      - 'Frontend/**'
      - 'Backend/**'
      - 'crates/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/development.yml'

concurrency:
  group: dev-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dev:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    env:
      RUSTC_WRAPPER: sccache
      SCCACHE_GHA_ENABLED: 'true'
      SCCACHE_CACHE_SIZE: '2G'
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          lfs: true

      # ---------- Frontend: lint + typecheck ----------
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: Frontend/package-lock.json

      - name: Install frontend deps
        working-directory: Frontend
        run: npm ci --no-audit --no-fund

      - name: Lint
        working-directory: Frontend
        run: npm run lint --if-present

      - name: Typecheck
        working-directory: Frontend
        run: npm run typecheck --if-present

      # ---------- Backend: cargo check ----------
      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Install Linux build deps
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libgtk-3-dev \
            libglib2.0-dev \
            libgdk-pixbuf-2.0-dev \
            libpango1.0-dev \
            libsoup-3.0-dev \
            libwebkit2gtk-4.1-dev
          pkg-config --modversion javascriptcoregtk-4.1

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Cargo check
        run: cargo check
