name: Dev CI (fast)

on:
  push:
    branches: [ Dev ]
  pull_request:
    branches: [ Dev ]

concurrency:
  group: dev-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dev:
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: false   # flip to true only if your checks actually read LFS blobs

      # ---------- Frontend: lint + typecheck only ----------
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: Frontend/package-lock.json

      - name: Install frontend deps
        working-directory: Frontend
        run: npm ci

      - name: Lint
        working-directory: Frontend
        run: npm run lint --if-present

      - name: Typecheck
        working-directory: Frontend
        run: npm run typecheck --if-present

      # ---------- Backend: cargo check only ----------
      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo (root workspace target/)
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Cargo check
        run: cargo check --all-features
